// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swagger_test/models"
)

// CreateTodoItemCreatedCode is the HTTP code returned for type CreateTodoItemCreated
const CreateTodoItemCreatedCode int = 201

/*CreateTodoItemCreated Created

swagger:response createTodoItemCreated
*/
type CreateTodoItemCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewCreateTodoItemCreated creates CreateTodoItemCreated with default headers values
func NewCreateTodoItemCreated() *CreateTodoItemCreated {

	return &CreateTodoItemCreated{}
}

// WithPayload adds the payload to the create todo item created response
func (o *CreateTodoItemCreated) WithPayload(payload *models.Item) *CreateTodoItemCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create todo item created response
func (o *CreateTodoItemCreated) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTodoItemCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateTodoItemInternalServerErrorCode is the HTTP code returned for type CreateTodoItemInternalServerError
const CreateTodoItemInternalServerErrorCode int = 500

/*CreateTodoItemInternalServerError error occured

swagger:response createTodoItemInternalServerError
*/
type CreateTodoItemInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateTodoItemInternalServerError creates CreateTodoItemInternalServerError with default headers values
func NewCreateTodoItemInternalServerError() *CreateTodoItemInternalServerError {

	return &CreateTodoItemInternalServerError{}
}

// WithPayload adds the payload to the create todo item internal server error response
func (o *CreateTodoItemInternalServerError) WithPayload(payload *models.Error) *CreateTodoItemInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create todo item internal server error response
func (o *CreateTodoItemInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateTodoItemInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
