// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swagger_test/models"
)

// DeleteTodoItemNoContentCode is the HTTP code returned for type DeleteTodoItemNoContent
const DeleteTodoItemNoContentCode int = 204

/*DeleteTodoItemNoContent Deleted

swagger:response deleteTodoItemNoContent
*/
type DeleteTodoItemNoContent struct {
}

// NewDeleteTodoItemNoContent creates DeleteTodoItemNoContent with default headers values
func NewDeleteTodoItemNoContent() *DeleteTodoItemNoContent {

	return &DeleteTodoItemNoContent{}
}

// WriteResponse to the client
func (o *DeleteTodoItemNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteTodoItemNotFoundCode is the HTTP code returned for type DeleteTodoItemNotFound
const DeleteTodoItemNotFoundCode int = 404

/*DeleteTodoItemNotFound Not Found

swagger:response deleteTodoItemNotFound
*/
type DeleteTodoItemNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTodoItemNotFound creates DeleteTodoItemNotFound with default headers values
func NewDeleteTodoItemNotFound() *DeleteTodoItemNotFound {

	return &DeleteTodoItemNotFound{}
}

// WithPayload adds the payload to the delete todo item not found response
func (o *DeleteTodoItemNotFound) WithPayload(payload *models.Error) *DeleteTodoItemNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete todo item not found response
func (o *DeleteTodoItemNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTodoItemNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteTodoItemDefault error

swagger:response deleteTodoItemDefault
*/
type DeleteTodoItemDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTodoItemDefault creates DeleteTodoItemDefault with default headers values
func NewDeleteTodoItemDefault(code int) *DeleteTodoItemDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTodoItemDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete todo item default response
func (o *DeleteTodoItemDefault) WithStatusCode(code int) *DeleteTodoItemDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete todo item default response
func (o *DeleteTodoItemDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete todo item default response
func (o *DeleteTodoItemDefault) WithPayload(payload *models.Error) *DeleteTodoItemDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete todo item default response
func (o *DeleteTodoItemDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTodoItemDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
