// Code generated by go-swagger; DO NOT EDIT.

package todo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swagger_test/models"
)

// FetchTodoItemsOKCode is the HTTP code returned for type FetchTodoItemsOK
const FetchTodoItemsOKCode int = 200

/*FetchTodoItemsOK fetch todo items

swagger:response fetchTodoItemsOK
*/
type FetchTodoItemsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Item `json:"body,omitempty"`
}

// NewFetchTodoItemsOK creates FetchTodoItemsOK with default headers values
func NewFetchTodoItemsOK() *FetchTodoItemsOK {

	return &FetchTodoItemsOK{}
}

// WithPayload adds the payload to the fetch todo items o k response
func (o *FetchTodoItemsOK) WithPayload(payload []*models.Item) *FetchTodoItemsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fetch todo items o k response
func (o *FetchTodoItemsOK) SetPayload(payload []*models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FetchTodoItemsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Item, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*FetchTodoItemsDefault error occured

swagger:response fetchTodoItemsDefault
*/
type FetchTodoItemsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFetchTodoItemsDefault creates FetchTodoItemsDefault with default headers values
func NewFetchTodoItemsDefault(code int) *FetchTodoItemsDefault {
	if code <= 0 {
		code = 500
	}

	return &FetchTodoItemsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the fetch todo items default response
func (o *FetchTodoItemsDefault) WithStatusCode(code int) *FetchTodoItemsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the fetch todo items default response
func (o *FetchTodoItemsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the fetch todo items default response
func (o *FetchTodoItemsDefault) WithPayload(payload *models.Error) *FetchTodoItemsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the fetch todo items default response
func (o *FetchTodoItemsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FetchTodoItemsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
