// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Todo list app
//
//  Todo Foo  bar
//  Schemes:
//    http
//  Host: 127.0.0.1:3000
//  BasePath: /
//  Version: 0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
